import os
import sys
import time
import subprocess

# 1. On-demand installation of fpdf2 inside the sandbox container
try:
    from fpdf import FPDF
except ImportError:
    print("[PDF Helper] Installing fpdf2 in sandbox...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "fpdf2"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    from fpdf import FPDF

# 2. Unicode Text Cleaner
# Standard PDF fonts like Helvetica only support Latin-1 (ASCII).
# Web-scraped text often contains Unicode characters (curly quotes, em-dashes, bullet points)
# which throw FPDFUnicodeEncodingException. This helper cleans them.
def clean_text(text: str) -> str:
    if not text or not isinstance(text, str):
        return ""
    
    # Replace common unsupported Unicode characters with ASCII equivalents
    replacements = {
        '\u201c': '"', '\u201d': '"', # Curly double quotes “ ”
        '\u2018': "'", '\u2019': "'", # Curly single quotes ‘ ’
        '\u2013': '-', '\u2014': '-', # En and em dashes – —
        '\u2022': '*',                 # Bullet point •
        '\u201a': ',',                 # Single low-9 quote
        '\u201e': ',,',                # Double low-9 quote
        '\u2026': '...',               # Ellipsis …
        '\u2122': 'TM',                # Trademark
        '\u00ae': '(R)',               # Registered
        '\u00a9': '(C)',               # Copyright
    }
    
    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)
        
    # Encode to Latin-1, ignoring any remaining unsupported characters, and decode back
    return text.encode('latin-1', 'ignore').decode('latin-1')

# 3. Define the PDF Layout
class FinancialReportPDF(FPDF):
    def header(self):
        self.set_fill_color(24, 43, 73)
        self.rect(0, 0, 210, 35, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.set_y(10)
        self.cell(0, 10, "INVESTMENT RESEARCH REPORT", border=False, ln=1, align="C")
        self.set_text_color(200, 200, 200)
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 5, "Autonomously Generated by Gemini Enterprise Agent", border=False, ln=1, align="C")
        self.set_text_color(33, 33, 33)
        self.set_y(40)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Confidential - For Internal Use Only", align="C")

def generate_pdf_report(filename: str, report_data: dict):
    pdf = FinancialReportPDF()
    pdf.add_page()
    
    # 1. Title Block
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(24, 43, 73)
    pdf.cell(0, 10, f"Equity Comparison: {', '.join(report_data['tickers'])}", ln=1)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Analysis Date: {time.strftime('%Y-%m-%d %H:%M:%S UTC')}", ln=1)
    pdf.ln(5)
    
    # 2. Market Data Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(24, 43, 73)
    pdf.cell(0, 8, "1. Real-Time Market Data (Yahoo Finance)", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    for ticker, price in report_data['current_prices'].items():
        pdf.cell(0, 6, f"- {ticker}: {clean_text(str(price))}", ln=1)
    pdf.ln(6)
    
    # 3. Executive Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(24, 43, 73)
    pdf.cell(0, 8, "2. Executive Summary & Market Intelligence", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(33, 33, 33)
    # Clean the summary text before writing to PDF
    pdf.multi_cell(0, 5, clean_text(report_data['summary']))
    pdf.ln(6)
    
    # 4. Recommendation & Sentiment
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(24, 43, 73)
    pdf.cell(0, 8, "3. Investment Thesis & Recommendation", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, f"Sentiment: {clean_text(report_data['sentiment'])}", ln=1)
    pdf.set_font("Helvetica", "", 9.5)
    # Clean the recommendation text before writing to PDF
    pdf.multi_cell(0, 5, clean_text(report_data['recommendation']))
    
    pdf.output(filename)
    print(f"[PDF Helper] PDF successfully written to {filename}")
